Update __init__.py
Fix YAML loading

```
Traceback (most recent call last):
  File "/usr/local/bin/dns-blackhole", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/local/lib/python3.13/site-packages/dnsblackhole/cli.py", line 4, in main
    dnsblackhole.main()
    ~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/dnsblackhole/__init__.py", line 326, in main
    config = load_config()
  File "/usr/local/lib/python3.13/site-packages/dnsblackhole/__init__.py", line 49, in load_config
    yaml_config = yaml.load(f)
TypeError: load() missing 1 required positional argument: 'Loader'
```